### PR TITLE
fix invalid connect options, when using browserURL

### LINKED ISSUE #200: Cannot read property 'removeListener' of undefined
## 🐛 Bug Report

Seems related to #192. Locally, the tests run fine, but when running our tests in CircleCI, we get the error:
```
[Jest Dev server] ℹ ｢wdm｣: Compiled successfully.
 FAIL  test/browser/tests/presentation.entry.js
  ● Test suite failed to run

    TypeError: Cannot read property 'removeListener' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:126:22)

 FAIL  test/browser/tests/login.entry.js
  ● Test suite failed to run

    TypeError: Cannot read property 'removeListener' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:126:22)

 FAIL  test/browser/tests/app.entry.js
  ● Test suite failed to run

    TypeError: Cannot read property 'removeListener' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:126:22)
```

I've tried clearing the CircleCI cache, but it doesn't help. I also tried adding a global teardown to no avail.

**Previously everything was working with:**
- "jest-puppeteer": "3.8.0"
- "jest": "23.6.0"
- "puppeteer": "1.11.0"

**It fails after updating to:**
- "jest-puppeteer": "3.9.0"
- "jest": "24.1.0"
- "puppeteer": "1.12.2"

Our `jest.config.js`:
```javascript
module.exports = {
  preset: 'jest-puppeteer',
  roots: ['<rootDir>/test/browser/'],
  testMatch: ['<rootDir>/test/browser/tests/*.entry.js'],
  transform: {
    '^.+\\.(js|jsx)?$': 'babel-jest',
  },
  verbose: true,
};
```

Our `jest-puppeteer.config.js`:
```javascript
const argv = process.execArgv.join();
const isDebugging =
  Boolean(process.env.debug) ||
  argv.includes('inspect') ||
  argv.includes('debug');
const slowMo = 100;
const browserSettings = isDebugging
  ? {
      devtools: true,
      headless: false,
      slowMo,
    }
  : {
      slowMo,
    };

module.exports = {
  launch: {
    defaultViewport: {
      width: 1920,
      height: 1080,
    },
    args: [
      '--window-size=1920,1080',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--homedir=/tmp',
      '--data-path=/tmp/data-path',
      '--disk-cache-dir=/tmp/cache-dir',
      '--remote-debugging-port=9222',
      '--proxy-server="direct://"',
      '--proxy-bypass-list=*',
    ].filter(Boolean),
    ...browserSettings,
    dumpio: true,
  },
  server: {
    command: 'yarn test:server',
    protocol: 'http',
    host: 'localhost',
    port: 8082,
    launchTimeout: 500000,
    usedPortAction: 'ignore',
    debug: true,
  },
};
```

### PR DESCRIPTION
**Pull request by backbone87**
## Summary

Specifying both options `browserURL` and `browserWSEndpoint` is invalid when calling connect. Since `PuppeteerEnvironment` always gets a WS endpoint prepared from global setup, we must unset the `browserURL` option.

Edit: Since this problem also exists in v3, it would be nice to backport this, since v4 does not support jest v23 anymore

Edit2: This most likely fixes #200, at least my occurence of it. The real problem is that setup exceptions get swallowed, if teardown also throws. Guessing that the jest code looks something like this:
```js
try {
  env.setup();
  test();
} catch(e) {
  env.teardown();
  throw e;
}
```
So the actual problem (setup failing) gets shadowed by the teardown fragility not being able to do its work on a dirty env.

### CODE REVIEW

**Comment by backbone87** [comment]
i have added some hardening into teardown, so it can handle most cases of dirty env

File: packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js [hunk 1]
```diff
@@ -115,16 +115,25 @@ class PuppeteerEnvironment extends NodeEnvironment {
...
   async teardown() {
-    const config = await readConfig()
-    this.global.page.removeListener('pageerror', handleError)
+    const { page, context, browser, puppeteerConfig } = this.global
 
-    if (config.browserContext === 'incognito') {
-      await this.global.context.close()
+    if (page) {
+      page.removeListener('pageerror', handleError)
+    }
```
Comment (MacZel) [inline packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js]: You are checking `if (page)` on line L120 and L129. If it's supposed to be run only if `page` is `true` you can combine those two if blocks into one. Logic would stay the same.

File: packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js [hunk 2]
```diff
@@ -115,16 +115,25 @@ class PuppeteerEnvironment extends NodeEnvironment {
...
+
+    if (puppeteerConfig.browserContext === 'incognito') {
+      if (context) {
+        await context.close()
+      }
     } else {
-      await this.global.page.close()
```
Comment (MacZel) [inline packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js]: tbh logic would stay the same if you will change lines L120-L132 to:
```
if (puppeteerConfig.browserContext === 'incognito' && context) {
  await context.close()
} else if (page) {
  page.removeListener('pageerror', handleError)
  await page.close()
}
```

File: packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js (hunk 1 above)
Comment (backbone87) [reply packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js]: This should be dont always, if page is set.

File: packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js (hunk 2 above)
Comment (backbone87) [reply packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js]: This code is different: If browserContent === 'incognito' && context, then page.removeListener, wont be called, but that call should only depend on existance of page.

```
if (puppeteerConfig.browserContext === 'incognito' && context) {
  await context.close()
} else if (page) {
  await page.close()
}
```
Normally this also changes the logic of the original block i posted, but since page and context depend on each other, so when browserContent === 'incognito' && context === undefined (because error in setup), it must be page === undefined, because there cant be a page without context.

**Comment by backbone87** [comment]
i have fixed the linting error, but imho in this special case, it decreases the readability of the code, because the inner if is independant to the outer if.

File: packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js (hunk 2 above)
Comment (backbone87) [reply packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js]: To extend on this: You must have knowledge about the dependency between context & page, to correctly understand the minified if/else you propose, which makes it harder to reason about what happens.

**Comment by neoziro** [comment]
Hello @backbone87, thanks for the fix, it looks better than before and it should fix the bug. I will merge it and release a new version.

**Comment by backbone87** [comment]
@neoziro can we have a backport to v3 for this?

**Comment by neoziro** [comment]
@backbone87 yes we can

**Comment by neoziro** [comment]
Published!
